// might delete later
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEFOU9pniukyDHTNbdqRX-bTRzhAUgE5M',
    appId: '1:493824810701:web:808cc3dd9094b7b2b7d384',
    messagingSenderId: '493824810701',
    projectId: 'medicinereminder-9a3fb',
    authDomain: 'medicinereminder-9a3fb.firebaseapp.com',
    storageBucket: 'medicinereminder-9a3fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsi1pzdbmlZQCSF5foEwib-fr4yG_fw8M',
    appId: '1:493824810701:android:5499c7985bf735a9b7d384',
    messagingSenderId: '493824810701',
    projectId: 'medicinereminder-9a3fb',
    storageBucket: 'medicinereminder-9a3fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_TcxIMNhrYgT0lwFiB_j-bbV4C5x9z9k',
    appId: '1:493824810701:ios:28baf4d9d8c9714cb7d384',
    messagingSenderId: '493824810701',
    projectId: 'medicinereminder-9a3fb',
    storageBucket: 'medicinereminder-9a3fb.appspot.com',
    iosClientId: '493824810701-s26pidlu8s75kvhccpave9ij0h3v0lls.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicinereminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_TcxIMNhrYgT0lwFiB_j-bbV4C5x9z9k',
    appId: '1:493824810701:ios:c5a3ac4e4a7a63dcb7d384',
    messagingSenderId: '493824810701',
    projectId: 'medicinereminder-9a3fb',
    storageBucket: 'medicinereminder-9a3fb.appspot.com',
    iosClientId: '493824810701-dc6q4m9sqs12unnnu7flbj0enu48qo41.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicinereminder.RunnerTests',
  );
}
